model_config:
  hidden_units: 100
  hidden_units_mlp: 50
  fgp_size: 50
  dropout: 0.27534647775698873
  lr: 0.0001
  l2: 0.05320428113500612
  num_layers: 3
  activation: relu
  dropout_flag: False
  concat: True
  fgp: False
train_config:
  epochs: 100
  batch: 32
