model_config:
  hidden_units: 64
  hidden_units_mlp: 200
  fgp_size: 50
  dropout: 0.401191219083158
  lr: 0.0001
  l2: 0.09871834597758934
  num_layers: 3
  activation: relu
  dropout_flag: False
  concat: True
  fgp: False
train_config:
  epochs: 150
  batch: 32
